# Generated by Django 5.2.9 on 2025-12-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_review_options_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reply_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='reply_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
