# Generated by Django 5.2.9 on 2026-01-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='slip_image',
            field=models.ImageField(blank=True, null=True, upload_to='slips/'),
        ),
    ]
