# Generated by Django 5.2.8 on 2025-12-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_deletedlog_product_image_product_is_edited_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeletedLog',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_edited',
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
