# Generated by Django 5.2.9 on 2026-01-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_order_bank_name_order_transfer_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transfer_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
