# Generated by Django 5.2.8 on 2026-01-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_tag_product_depth_product_height_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
