# Generated by Django 5.2.10 on 2026-01-14 01:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_order_shipping_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='รหัสคูปอง (e.g. SALE50)', max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage (%)'), ('fixed', 'Fixed Amount (THB)')], default='fixed', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='มูลค่าส่วนลด', max_digits=10)),
                ('min_spend', models.DecimalField(decimal_places=2, default=0, help_text='ยอดซื้อขั้นต่ำ', max_digits=10)),
                ('usage_limit', models.IntegerField(default=100, help_text='จำนวนสิทธิ์ทั้งหมด')),
                ('used_count', models.IntegerField(default=0, help_text='ใช้ไปแล้ว')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'coupons',
                'ordering': ['-end_date'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='myapp.coupon'),
        ),
    ]
