# Generated by Django 5.2.8 on 2026-01-14 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_coupon_order_discount_amount_order_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'flash_sales',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_use_per_user',
            field=models.IntegerField(default=1, help_text='จำกัดสิทธิ์ต่อคน'),
        ),
        migrations.CreateModel(
            name='FlashSaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_limit', models.IntegerField(default=10, help_text='จำนวนสินค้าที่จัดโปร')),
                ('sold_count', models.IntegerField(default=0)),
                ('flash_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='myapp.flashsale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sales', to='myapp.product')),
            ],
            options={
                'db_table': 'flash_sale_products',
                'unique_together': {('flash_sale', 'product')},
            },
        ),
    ]
