# Generated by Django 5.2.8 on 2026-01-16 02:26

import myapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_flashsale_coupon_max_use_per_user_flashsaleproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='allowed_roles',
            field=models.JSONField(blank=True, default=list, help_text="Roles that can use this coupon (e.g. ['member', 'vip'])"),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, validators=[myapp.validators.validate_product_name]),
        ),
    ]
