# Generated by Django 5.2.10 on 2026-01-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_coupon_allowed_roles_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsale',
            name='description',
            field=models.TextField(blank=True, help_text='รายละเอียดแคมเปญ', null=True),
        ),
    ]
