# Generated by Django 5.2.10 on 2026-01-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_flashsale_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage (%)'), ('fixed', 'Fixed Amount (THB)'), ('free_shipping', 'Free Shipping')], default='fixed', max_length=20),
        ),
    ]
