# Generated by Django 5.2.10 on 2026-01-19 09:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_review_image_alter_coupon_discount_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock_reservations',
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Ready to use'), ('used', 'Used'), ('expired', 'Expired'), ('locked', 'Locked in pending order')], default='active', max_length=20)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_coupons',
            },
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='max_use_per_user',
        ),
        migrations.AddField(
            model_name='coupon',
            name='auto_apply',
            field=models.BooleanField(default=False, help_text='ระบบเลือกให้อัตโนมัติ'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, help_text='Advanced rules (e.g. specific SKU, exclude category)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, help_text='เงื่อนไขการใช้ (User-facing)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_public',
            field=models.BooleanField(default=True, help_text='แสดงใน Coupon Center'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_stackable_with_flash_sale',
            field=models.BooleanField(default=False, help_text='ใช้ร่วมกับ Flash Sale ได้ไหม (Strict Rule)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='limit_per_user',
            field=models.IntegerField(default=1, help_text='จำกัดสิทธิ์ต่อคน (ตลอดแคมเปญ)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='limit_per_user_per_day',
            field=models.IntegerField(default=0, help_text='จำกัดสิทธิ์ต่อคนต่อวัน (0 = ไม่จำกัด)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ลดสูงสุดไม่เกิน (สำหรับ Capped Percent)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='name',
            field=models.CharField(blank=True, help_text='ชื่อแคมเปญ (Internal)', max_length=255),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='flash_sales/'),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='priority',
            field=models.IntegerField(default=0, help_text='ลำดับความสำคัญ (กรณีเวลาชนกัน)'),
        ),
        migrations.AddField(
            model_name='flashsaleproduct',
            name='limit_per_user',
            field=models.IntegerField(default=1, help_text='จำกัดจำนวนซื้อต่อคน'),
        ),
        migrations.AddField(
            model_name='flashsaleproduct',
            name='original_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='flashsaleproduct',
            name='reserved_stock',
            field=models.IntegerField(default=0, help_text='จำนวนที่ถูกจองรอจ่ายเงิน'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='flash_sale_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='item_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='base_price_at_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='promotion_ref_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='promotion_source',
            field=models.CharField(choices=[('normal', 'Normal Price'), ('flash_sale', 'Flash Sale'), ('coupon_prorate', 'Coupon Prorated')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='allowed_roles',
            field=models.JSONField(blank=True, default=list, help_text='Roles: member, vip, etc.'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(db_index=True, help_text='รหัสคูปอง (e.g. SALE50)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage (%)'), ('fixed', 'Fixed Amount (THB)'), ('free_shipping', 'Free Shipping'), ('capped_percent', 'Capped Percentage (%)')], default='fixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.IntegerField(default=100, help_text='จำนวนสิทธิ์ทั้งหมด (Global)'),
        ),
        migrations.AlterField(
            model_name='flashsale',
            name='end_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='flashsale',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='flashsaleproduct',
            name='quantity_limit',
            field=models.IntegerField(default=10, help_text='จำนวนสินค้าที่จัดโปร (Total Quota)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_orders', to='myapp.coupon'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='coupons_code_94ae53_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['start_date', 'end_date'], name='coupons_start_d_54f583_idx'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='flash_sale_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.flashsaleproduct'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_collections', to='myapp.coupon'),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='order_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_coupon_wallet', to='myapp.order'),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='applied_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='myapp.usercoupon'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['expires_at'], name='stock_reser_expires_fdd22d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercoupon',
            unique_together={('user', 'coupon')},
        ),
    ]
