# Generated by Django 5.2.8 on 2026-01-20 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_stockreservation_usercoupon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_type', models.CharField(choices=[('coupon', 'Coupon'), ('flash_sale', 'Flash Sale')], max_length=20)),
                ('promo_id', models.IntegerField(help_text='ID of Coupon or FlashSale')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('priority', models.IntegerField(default=0)),
                ('impact_scope', models.JSONField(default=dict, help_text="Scope e.g. {'type': 'global'} or {'type': 'category', 'ids': [1]}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'promotion_schedules',
            },
        ),
        migrations.CreateModel(
            name='PromoUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_type', models.CharField(max_length=20)),
                ('promo_id', models.IntegerField()),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'promo_usage_logs',
            },
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-priority', '-end_date']},
        ),
        migrations.AddField(
            model_name='coupon',
            name='priority',
            field=models.IntegerField(default=0, help_text='ลำดับความสำคัญ (Higher = Better)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='target_user_roles',
            field=models.JSONField(blank=True, default=list, help_text='Target Group logic'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='tiered_rules',
            field=models.JSONField(blank=True, default=list, help_text="e.g. [{'min':1000, 'disc':100}, {'min':3000, 'disc':500}]"),
        ),
        migrations.AddField(
            model_name='coupon',
            name='total_supply',
            field=models.IntegerField(default=1000000, help_text='จำนวนสิทธิ์ทั้งหมด (Global Limit)'),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='limit_per_user_total',
            field=models.IntegerField(default=5, help_text='จำกัดจำนวนชิ้นรวมต่อคนในแคมเปญนี้'),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='rounds',
            field=models.JSONField(blank=True, default=list, help_text="Sub-rounds e.g. [{'start': '10:00', 'end': '12:00'}]"),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage (%)'), ('fixed', 'Fixed Amount (THB)'), ('free_shipping', 'Free Shipping'), ('capped_percent', 'Capped Percentage (%)'), ('tiered', 'Tiered Discount')], default='fixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.IntegerField(default=100, help_text='จำนวนสิทธิ์ทั้งหมด (Legacy field)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='used_count',
            field=models.IntegerField(default=0, help_text='ใช้ไปแล้ว (Atomic)'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['priority'], name='coupons_priorit_cf8a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionschedule',
            index=models.Index(fields=['start_time', 'end_time'], name='promotion_s_start_t_dce80c_idx'),
        ),
        migrations.AddField(
            model_name='promousagelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
