# Generated by Django 5.2.8 on 2026-01-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_promotionschedule_promousagelog_alter_coupon_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsale',
            name='auto_disable_on_end',
            field=models.BooleanField(default=True, help_text='ปิดการใช้งานอัตโนมัติเมื่อถึงเวลา end_time'),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='enable_notification',
            field=models.BooleanField(default=True, help_text='เปิดการแจ้งเตือนไปยังผู้ใช้'),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='limit_per_user_enabled',
            field=models.BooleanField(default=True, help_text='บังคับใช้ limit_per_user_total (ปิดเพื่อไม่จำกัด)'),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='show_countdown_timer',
            field=models.BooleanField(default=True, help_text='แสดง Countdown Timer ในหน้า Flash Sale'),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='show_in_hero',
            field=models.BooleanField(default=True, help_text='แสดงสินค้าในส่วน Hero Banner ของหน้าแรก'),
        ),
    ]
