# Generated by Django 5.2.8 on 2026-01-22 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_flashsale_auto_disable_on_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsale',
            name='display_order',
            field=models.IntegerField(default=0, help_text='ลำดับการแสดงผลบน Timeline (เรียงจากน้อยไปมาก)'),
        ),
        migrations.CreateModel(
            name='FlashSaleCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="ชื่อแคมเปญ เช่น 'Mega Sale Phase 1', 'Double Day 11.11'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='รายละเอียดแคมเปญ (Internal use)')),
                ('campaign_start', models.DateTimeField(db_index=True, help_text='วันเริ่มต้นแคมเปญ (ครอบคลุม Flash Sale ทั้งหมดข้างใน)')),
                ('campaign_end', models.DateTimeField(db_index=True, help_text='วันสิ้นสุดแคมเปญ')),
                ('banner_image', models.ImageField(blank=True, help_text='รูป Banner สำหรับแคมเปญนี้', null=True, upload_to='campaigns/')),
                ('theme_color', models.CharField(default='#f97316', help_text='สีธีมของแคมเปญ (HEX format เช่น #ff6600)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='เปิด/ปิดการใช้งานแคมเปญ')),
                ('priority', models.IntegerField(default=0, help_text='ลำดับความสำคัญ (ใช้เรียงลำดับแสดงผล)')),
            ],
            options={
                'db_table': 'flash_sale_campaigns',
                'ordering': ['-campaign_start', '-priority'],
                'indexes': [models.Index(fields=['campaign_start', 'campaign_end'], name='flash_sale__campaig_286e28_idx'), models.Index(fields=['is_active'], name='flash_sale__is_acti_b8f50a_idx')],
            },
        ),
        migrations.AddField(
            model_name='flashsale',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='แคมเปญที่ Flash Sale นี้เป็นส่วนหนึ่ง (Optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flash_sales', to='myapp.flashsalecampaign'),
        ),
    ]
