# Generated by Django 5.2.8 on 2025-12-23 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='created_at',
        ),
    ]
