# Generated by Django 5.2.8 on 2026-01-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_fix_order_auto_increment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashsalecampaign',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
