# Generated by Django 5.2.10 on 2026-01-29 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_flashsalecampaign_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.AddField(
            model_name='product',
            name='admin',
            field=models.ForeignKey(blank=True, db_column='admin_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('new_user', 'New User'), ('customer', 'Customer'), ('admin', 'Super Admin')], default='new_user', max_length=20),
        ),
    ]
