# Generated by Antigravity on 2026-01-29

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_product_seller_product_admin_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='วันหมดอายุของ Tag (เช่น Tag โปรโมชั่นชั่วคราว)', null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='automation_rules',
            field=models.JSONField(blank=True, default=dict, help_text="Logic สำหรับ Automation (e.g. {'if': 'price > 1000', 'then': 'auto_tag'})"),
        ),
    ]
