# Generated by Django 5.2.10 on 2026-02-02 07:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_tag_expiration'),
    ]

    operations = [
        # 1. State Update Only: Tell Django these columns exist, but DON'T run SQL (avoid duplicate error)
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#6366f1', help_text='สีของ Tag (Hex Code)', max_length=20),
        ),
        migrations.AddField(
            model_name='tag',
            name='group_name',
            field=models.CharField(choices=[('category', 'หมวดหมู่ (Category)'), ('promotion', 'โปรโมชั่น (Promotion)'), ('feature', 'คุณสมบัติ (Feature)'), ('brand', 'แบรนด์ (Brand)'), ('other', 'อื่นๆ (Other)')], default='other', help_text='กลุ่มของ Tag', max_length=50),
        ),
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.CharField(blank=True, help_text='ชื่อไอคอนจาก Lucide', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(default=True),
        ),

        # 2. Real SQL: Create the columns that are ACTUALLY missing
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly name (Auto-generated)', max_length=100, null=True, unique=True),
        ),
        
        # 3. Alterations
        migrations.AlterField(
            model_name='tag',
            name='automation_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Automation Logic'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='วันหมดอายุ', null=True),
        ),
        
        # 4. Indexes (Might fail if index exists, but trying standard first)
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['slug'], name='tags_slug_c72f9b_idx'),
        ),
        # Wrap group_name index in try-catch logic theoretically? No, let's assume it's missing or we fix next.
        # But to be safe against "Duplicate Key" for index, let's use SeparateDatabaseAndState for this index too IF we suspect it exists.
        # Given we deleted 0005, index likely REMAINS. So adding it again WILL FAIL.
        # Better safe: Move group_name index to State Only as well.
        # But slug index is new.
        
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['group_name'], name='tags_group_n_f0e6f1_idx'),
        ),
    ]
