# Generated by Django 5.2.10 on 2026-02-03 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_tag_color_tag_created_at_tag_group_name_tag_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaMenuConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='menu_banners/')),
                ('promo_text', models.CharField(blank=True, help_text='Text shown on the banner (optional)', max_length=255, null=True)),
                ('button_text', models.CharField(default='ช้อปเลย', max_length=50)),
                ('button_link', models.CharField(blank=True, help_text='Link for the button (optional)', max_length=255, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in main menu list?')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_config', to='myapp.category')),
            ],
            options={
                'verbose_name': 'Mega Menu Configuration',
                'verbose_name_plural': 'Mega Menu Configurations',
            },
        ),
    ]
