# Generated by Django 5.2.11 on 2026-02-04 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_order_courier_name_order_shipped_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('initial_price', models.DecimalField(decimal_places=2, help_text='ราคาตอนเพิ่มเข้า Wishlist', max_digits=10)),
                ('notify_on_drop', models.BooleanField(default=True, help_text='แจ้งเตือนเมื่อราคาลด')),
                ('last_price_check', models.DateTimeField(auto_now=True, help_text='ตรวจสอบราคาล่าสุดเมื่อไหร่')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='myapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wishlist',
                'ordering': ['-added_date'],
                'indexes': [models.Index(fields=['user', '-added_date'], name='wishlist_user_id_1fe3d8_idx'), models.Index(fields=['product'], name='wishlist_product_ab5d67_idx')],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
