# Generated by Django 5.2.11 on 2026-02-05 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_user_latitude_user_longitude_user_province_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address_detail', models.TextField(help_text='บ้านเลขที่, หมู่, อาคาร, ซอย, ถนน')),
                ('sub_district', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('label', models.CharField(choices=[('Home', 'บ้าน'), ('Work', 'ที่ทำงาน'), ('Other', 'อื่นๆ')], default='Home', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shipping Addresses',
                'db_table': 'shipping_addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
