# Generated by Django 5.2.8 on 2026-02-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_order_cancelled_at_order_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='accuracy',
            field=models.CharField(blank=True, help_text='Accuracy level: building, house, road, street, city, etc.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='verified',
            field=models.BooleanField(default=False, help_text='User confirmed this is the actual location'),
        ),
    ]
