FROM python:3.13-slim

ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE myporject.settings

WORKDIR /usr/src/app

# ติดตั้ง dependencies ทีเดียวจบ
RUN apt-get update && \
    apt-get install -y default-libmysqlclient-dev gcc pkg-config && \
    pip install --no-cache-dir django djangorestframework mysqlclient django-cors-headers requests

COPY . /usr/src/app/

# สั่งรัน Server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]